### ISSUE TITLE
Adding custom effect strings

### ISSUE THREAD

**Issue by DuDono** [piface314/ygo-fabrica#24]
What I mean by "custom effect strings" is strings like the 'draw 1 card ?" that will pop up after using the effect of a co-linked Knightmare. I dunno how to add these, and the wiki didn't help.

**Comment by piface314** [comment]
In order for `ygofab make` to add custom effect strings, you just have to add `strings` to a cards entry, as explained [here](https://github.com/piface314/ygo-fabrica/wiki/Creating-cards#card-data). It should be an array of strings.

Example from [Knightmare Unicorn](https://yugipedia.com/wiki/Knightmare_Unicorn):

```toml
[[card]]
id = 38342335
name = "Knightmare Unicorn"
type = "monster effect link"
link-rating = 3
link-arrows = "left right bottom"
attribute = "dark"
race = "fiend"
atk = 2200
strings = ["Return to deck", "Draw 1 card?"]
# effect and set fields were omitted 
```
